# Generated by Django 4.1.7 on 2023-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_gender_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="please upload 48px * 48px size png/jpg.",
                upload_to="accounts/avatar/%Y/%m/%d",
            ),
        ),
    ]
