# Generated by Django 4.1.7 on 2023-03-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(upload_to="instagram/post/%Y/%m/%d"),
        ),
    ]
